### ISSUE TITLE
Bulk DELETE and/or Bulk PUT Target APIs

### ISSUE THREAD

**Issue by lizziemac** [eclipse-hawkbit/hawkbit#1851]
Are there bulk deletion and bulk update endpoints for targets? Right now, when I have devices self-register, I either need to delete them all, or update them all. As it stands, I currently have to iterate over a list of them, and call the API for each, individually.

If I can delete them all, this works because I'm already creating new (non-preregistered) devices after the above iteration, and I can just expand that to be all devices.

If I can update them all with a PUT, it would be even easier to fix them.

Related issue, that was answered: https://github.com/eclipse/hawkbit/issues/1842

Edit: I also noticed that the old UI would let you select and delete 1000 devices at once. Is this just a vaadin feature?

**Comment by strailov** [comment]
Hello @lizziemac , thanks for using hawkBit! 

Unfortunately there is no bulk update/delete of targets currently in hawkbit :(

**Comment by lizziemac** [comment]
Thanks for the info - perhaps it would be worth introducing. I think I have a workaround though - I'm planning on using hawkbit eventing anyways, so I may actually just listen for devices that self create/register and delete them when they join.
