### ISSUE TITLE
CORS Error with Hawkbit Frontend

### ISSUE THREAD

**Issue by FabioPetry18** [eclipse-hawkbit/hawkbit#1913]
Subject: 

Hello everyone,

I'm new to the community and currently using the latest version of Hawkbit. I'm encountering a CORS error with the frontend I've created.

Could someone please guide me on how to resolve this issue? Any tips or recommendations would be greatly appreciated!

Thank you!

![image](https://github.com/user-attachments/assets/946dc881-d98b-4d21-83c0-ce788fbe64e5)

docker: 
`version: '3'

services:

  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: "hawkbit"
      # MYSQL_USER: "root" is created by default in the container for mysql 8.0+
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    labels:
      NAME: "mysql"

  # ---------------------
  # HawkBit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
    volumes:
      - artifactrepo:/artifactrepo
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      NAME: "hawkbit"
volumes:
  artifactrepo:
    driver: local
`

**Comment by avgustinmm** [comment]
Hi, 
you could check if [HawkbitSecurityProperties](hawkbit-security-core/src/main/java/org/eclipse/hawkbit/security/HawkbitSecurityProperties.java) configuration - and especially Cors - would allow you to configure cors properly. E.g. with something like:
```properties
hawkbit.server.security.cors.enabled=true
hawkbit.server.security.cors.allowedOrigins=<your site>
```

**Comment by strailov** [comment]
@FabioPetry18 any success with the suggestion Avgustin gave ?  If this worked, could we close the issue ?

**Comment by FabioPetry18** [comment]
sure! it's works
