### ISSUE TITLE
New Hawkbit docker container whitelabel screen

### ISSUE THREAD

**Issue by JHarding86** [eclipse-hawkbit/hawkbit#1917]
So I have just setup the docker container by running this command:
`docker run -d --name hawkbit -p 8080:8080 hawkbit/hawkbit-update-server`
This seems to work fine, and `docker container ls` shows the following:
![image](https://github.com/user-attachments/assets/aff55625-121f-4b5f-a510-b990f25e52de)

When I first try to access "http://localhost:8080" I see this page:
![image](https://github.com/user-attachments/assets/9166f16e-cfef-4b03-a518-cae94188db42)

If I visit "http://localhost:8080" once more then I am redirected here:
http://localhost:8080/swagger-ui/index.html?attribute=redirectWithRedirectView
![image](https://github.com/user-attachments/assets/2a064870-a46e-4085-826f-9fb8e0d49ec8)

If I try to go to "http://localhost:8080/UI" as I have seen to access the management page, I get the whitelabel error page again.

Has something changed that all of the documentation is missing? Why am I not able to access the management UI?

**Comment by JHarding86** [comment]
Ok, did some searching. The UI has been removed. Is there a tutorial anywhere on how to use hawkbit? Where are the 3rd party management UIs?

**Comment by strailov** [comment]
Hello @JHarding86. 
Indeed the UI was removed. You could try using the hawkbit-simple-ui as it provides basic functionality. 
You could also check the [documentation](https://eclipse.dev/hawkbit/) for some APIs and concepts  explained.
