### ISSUE TITLE
Exception when trying to use example docker runtime

### ISSUE THREAD

**Issue by nealjack** [eclipse-hawkbit/hawkbit#1952]
I'm looking into updating my hawkbit installation from 0.3.0 to the most recent 0.6.1. I understand there have been substantial changes in regards to the UI and now there is an additional microservice for a simple UI.

I have attempted to run the docker compose script from [here](https://github.com/eclipse-hawkbit/hawkbit/blob/master/hawkbit-runtime/docker/docker-compose-monolith-mysql-with-simple-ui.yml). I was assuming I would just have to change to SPRING_APPLICATION_JSON to point to localhost instead of `hawkbit` like so:
```
- 'SPRING_APPLICATION_JSON={"hawkbit.server.mgmtUrl": "http://localhost:8080"}'
```

However, when navigating to the UI (`localhost:8088`), logging in, and then attempting to navigate to any link in the toolbar, I get the following error:
```
There was an exception while trying to navigate to 'targets' with the root cause 'org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused'
```

The [guide](https://eclipse.dev/hawkbit/guides/runhawkbit/) linked in the README seems to be very out of date. Is there any up to date documentation for running the newer versions of hawkbit with the UI in a docker container?

Thanks!

**Comment by strailov** [comment]
Seems like an instance of the hawkbit-update-server has not been started. Could you provide some more logs from the container related with this image ?

**Comment by strailov** [comment]
Also I would leave the SPRING_APPLICATION_JSON to point to hawkbit. Localhost is different for the network in docker-compose.

**Comment by nealjack** [comment]
I changed the SPRING_APPLICATION_JSON  to point at hawkbit and am receiving the same error:
```
There was an exception while trying to navigate to 'targets' with the root cause 'org.apache.hc.client5.http.HttpHostConnectException: Connect to http://hawkbit:8080 [hawkbit/172.18.0.5] failed: Connection refused'
```

I have attached the logs for the update server and the simple ui container, as well as my docker compose file (which should be the same as the one in the repo).

[update_server.txt](https://github.com/user-attachments/files/17682053/update_server.txt)
[simple_ui.txt](https://github.com/user-attachments/files/17682054/simple_ui.txt)
[docker-compose.txt](https://github.com/user-attachments/files/17682040/docker-compose.txt)

**Comment by strailov** [comment]
Looks like simple UI is trying to connect at 
17:17:15.765Z 
But Hawkbit is fully started at 
17:17:36.780Z

I would try and wait a bit after docker compose starts.

**Comment by nealjack** [comment]
I left it running for 20 minutes and while it is no longer throwing that exception. There are no links to any of the pages (like targets, distributions, etc) in the toolbar.

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                    PORTS                                                                                                                                                 NAMES
4657121231ed   hawkbit/hawkbit-update-server:latest-mysql   "sh -c 'java ${JAVA_…"   21 minutes ago   Up 21 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                                                                             nealjack-hawkbit-1
1ffd6fac12cd   mysql:8.0                                    "docker-entrypoint.s…"   21 minutes ago   Up 21 minutes (healthy)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                                                                                  nealjack-mysql-1
0eb4533573dc   hawkbit/hawkbit-simple-ui:latest-mysql       "sh -c 'java ${JAVA_…"   21 minutes ago   Up 21 minutes             8080/tcp, 0.0.0.0:8088->8088/tcp, :::8088->8088/tcp                                                                                                   nealjack-hawkbit-simple-ui-1
6e2662bc886e   rabbitmq:3-management                        "docker-entrypoint.s…"   21 minutes ago   Up 21 minutes             4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   nealjack-rabbitmq-1
```
![image](https://github.com/user-attachments/assets/8f06749e-9d06-4497-9fdf-1ca801b491e7)

[simple_ui.txt](https://github.com/user-attachments/files/17757419/simple_ui.txt)
[update_server.txt](https://github.com/user-attachments/files/17757437/update_server.txt)

**Comment by strailov** [comment]
I tried it locally on my machine with the **exact same** docker-compose file as it is in the repo. Currently I am able to log in and list my targets and entities. 
It seems there is some network problem when you are using docker-compose ... Some of my advices : 
- Check if rabbitmq and mysql images logs and see if everything is ok there ... 
- try opening the simple UI in incognito tab
- Also how do you login - the default user/pass is admin/admin as I see the username on the screenshot but check the password also ...

**Comment by nealjack** [comment]
Okay so my issue was I was logging in as admin/guest. It resulted in a successful log in but had no access to anything. Is this expected to be able to log in with an incorrect password?

Logging into admin/admin worked and I see and can access the various tabs of the UI.

**Comment by nealjack** [comment]
This may be unrelated - let me know if I should make a different issue, but I'm having trouble getting a custom password working for the hawkbit and simple-ui.

Previously, on 0.3.1, I specified a password through the SPRING_APPLICATION_JSON environment variable in a custom entrypoint like so:

```
export SPRING_APPLICATION_JSON='{
          "spring.datasource.url": "jdbc:mariadb://mysql:3306/hawkbit?allowPublicKeyRetrieval=true",
          "spring.rabbitmq.host": "rabbitmq",
          "spring.rabbitmq.username": "guest",
          "spring.rabbitmq.password": "guest",
          "spring.datasource.username": "root",
          "spring.datasource.password": "'${MYSQL_PASSWORD}'",
          "hawkbit.server.im.users[0].username": "admin",
          "hawkbit.server.im.users[0].password": "{noop}'${HAWKBIT_PASSWORD}'",
          "hawkbit.server.im.users[0].firstname": "Eclipse",
          "hawkbit.server.im.users[0].lastname": "HawkBit",
          "hawkbit.server.im.users[0].permissions": "ALL",
          "server.port": 8080,
          "server.servlet.session.timeout": "30m",
          "server.forward-headers-strategy": "NATIVE",
          "hawkbit.artifact.url.protocols.download-http.rel": "download-http",
          "hawkbit.artifact.url.protocols.download-http.protocol": "http",
          "hawkbit.artifact.url.protocols.download-http.port": 80,
          "hawkbit.artifact.url.protocols.download-http.hostname": "hawkbit.blueirislabs.com",
          "hawkbit.artifact.url.protocols.download-http.ref": "{protocol}://{hostname}:{port}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}"
        }'

        java ${JAVA_OPTS} org.springframework.boot.loader.launch.JarLauncher
```

The passwords are environment variables sourced from files created through docker secrets. If I echo this variable before launching the java application, I see that the passwords are being passed correctly. However, logging in with that password is unsuccessful and the default admin:admin is the only thing that works.

Thanks for any suggestions!

**Comment by strailov** [comment]
Hey @nealjack 
On the first question (for the UI) it is not intended to log in with wrong credentials. However as mentioned Simple UI is experimental and does not handle use cases like wrong password entered and so on - it just does not work when this happens :) 

On the second one 
If you are trying to change the login credentials for hawkbit I didnt see the proper properties exported. I think those are the one : 

`
hawkbit.username=admin
hawkbit.password=admin
`
If you could give it a try with those ? With the desired password of course.

**Comment by nealjack** [comment]
Okay thank you for the clarification!

Are the changed properties documented anywhere? I'm concerned other properties I am trying to configure are also incorrect.

**Comment by strailov** [comment]
Yes, but from the above comment I cannot see you passing the SPRING_APPLICATION_JSON to the spring application. 
Correct me If I am wrong but doesn't it need to be something like :
`java -jar -Dspring.application.json=${SPRING_APPLICATION_JSON} org.springframework.boot.loader.launch.JarLauncher `

**Comment by avgustinmm** [comment]
Note that just adding this hawkbit user won't remove the admin/admin. So, you'd probably will want to change its password in order to prevent access with default one

**Comment by nealjack** [comment]
Thank you for those links.

I got it running with a non-default password! If anyone runs into a similar problem, here is an example custom Dockerfile and entrypoint. It relies on docker secrets the pass a mysql and hawkbit password to the container. In a docker compose I am providing the HAWKBIT_PASSWORD_FILE and MYSQL_PASSWORD_FILE environment variables that point to the docker secret file locations. For example: `/run/secrets/hawkbit_password` and `/run/secrets/mysql_password`, respectively.

**Dockerfile**
```
FROM hawkbit/hawkbit-update-server:latest-mysql

USER root

RUN apk update && apk add bash

COPY entrypoint.sh /entrypoint.sh

ENV JAVA_OPTS="-Dspring.profiles.active=mysql -Xms768m -Xmx768m -XX:MaxMetaspaceSize=250m -XX:MetaspaceSize=250m -Xss300K -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError"

ENTRYPOINT ["/entrypoint.sh"]
```

**entrypoint.sh**
```
#!/usr/bin/env bash

if [[ -z "${HAWKBIT_PASSWORD_FILE}" ]]; then
  HAWKBIT_PASSWORD="admin"
else
  HAWKBIT_PASSWORD=$(cat ${HAWKBIT_PASSWORD_FILE})
fi

if [[ -z "${MYSQL_PASSWORD_FILE}" ]]; then
  MYSQL_PASSWORD=""
else
  MYSQL_PASSWORD=$(cat ${MYSQL_PASSWORD_FILE})
fi

# generate hawkbit configuration variable
export SPRING_APPLICATION_JSON='{
          "spring.rabbitmq.host": "rabbitmq",
          "spring.rabbitmq.username": "guest",
          "spring.rabbitmq.password": "guest",
          "spring.datasource.url": "jdbc:mariadb://mysql:3306/hawkbit?allowPublicKeyRetrieval=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "'${MYSQL_PASSWORD}'",
          "hawkbit.security.user.admin.tenant": "admin",
          "hawkbit.security.user.admin.password": "{noop}'${HAWKBIT_PASSWORD}'",
          "server.port": 8080,
          "server.servlet.session.timeout": "30m",
          "server.forward-headers-strategy": "NATIVE",
          "hawkbit.artifact.url.protocols.download-http.rel": "download-http",
          "hawkbit.artifact.url.protocols.download-http.protocol": "http",
          "hawkbit.artifact.url.protocols.download-http.port": 80,
          "hawkbit.artifact.url.protocols.download-http.hostname": "your-url.com",
          "hawkbit.artifact.url.protocols.download-http.ref": "{protocol}://{hostname}:{port}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}"
        }'

echo $SPRING_APPLICATION_JSON

# original entrypoint of the hawkbit image
java ${JAVA_OPTS} org.springframework.boot.loader.launch.JarLauncher
```
