### ISSUE TITLE
Cors error in server - localhost

### ISSUE THREAD

**Issue by FabioPetry18** [eclipse-hawkbit/hawkbit#1963]
Previously I reported a cors problem in my docker application with my localhost, now I have a different situation, my hawkbit is running on a server that cannot ping my machine, that is, I cannot put the addresses in the parameters, is there anything solution for this? It's a test server so it wouldn't be a problem if they released it to all hosts

**Comment by strailov** [comment]
Hello @FabioPetry18 
I am not sure I fully understood the issue. Is it CORS related or ? Could you please give some more insights ? 
Thanks!

**Comment by FabioPetry18** [comment]
It's about cors between a test server where hawkbit is and my localhost, the server can't access my machine so I can't specify the host in the parameter 
      - hawkbit.server.security.cors.allowedOrigins=http://localhost:4200,http://localhost:8088

I wanted to know if there is a way to disable it?

**Comment by strailov** [comment]
Maybe you can try setting 
 hawkbit.server.security.cors.allowedOrigins=* if this could work, however maybe it is not the best practice :)

**Comment by FabioPetry18** [comment]
adding  
hawkbit.server.security.cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS,HEAD
hawkbit.server.security.cors.allowedHeaders=Content-Type,Authorization,Accept
hawkbit.server.security.cors.allowCredentials=true
hawkbit.server.security.cors.enabled=true
hawkbit.server.security.cors.allowedOrigins=VPN PUBLIC IP
and VPN ip public works!
