### ISSUE TITLE
AssignDS Error

### ISSUE THREAD

**Issue by FabioPetry18** [eclipse-hawkbit/hawkbit#2026]
I'm trying to use the /rest/v1/targets/{controllerID}/assignedDS endpoint, but it doesn't respect the scheduled update time, or it returns skip or updates immediately, am I doing something wrong?

body: 

[
    {
        "id": "2",
        "confirmationRequired": false,
        "type": "soft",
        "maintenanceWindow": {
            "schedule": "0 50 18 13 11 ? 2024",
            "duration": "23:59:00",
            "timezone": "+03:00"
        }
    }
]

**Comment by avgustinmm** [comment]
Hi @FabioPetry18 ,
what do you mean by "skip or update immediately"? AFAIK, the maintenance window is just an instruction to the controller when to perform the software update. However, hawkBit will return the update on every poll.

**Comment by Edu4rdo00** [comment]
`maintenanceWindow` Always Returning as "unavailable" in Hawkbit + SWUpdate**

I'm experiencing issues when configuring the `maintenanceWindow` between Hawkbit 0.6.1 and SWUpdate 2023.05. No matter how I configure the maintenance window, it consistently returns as "unavailable" in the SWUpdate logs.

Here is an example of the request I'm using to set the maintenance window:

```bash
curl -v --location 'http://127.0.0.1/rest/v1/targets/SO-0027-362541571a04/assignedDS' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
--data '[
    {
        "id": "2",
        "confirmationRequired": false,
        "type": "soft",
        "maintenanceWindow": {
            "schedule": "0 30 10 14 11 ? 2024",
            "duration": "23:59:00",
            "timezone": "-03:00"
        }
    }
]'
```

Despite configuring the cron correctly and verifying the synchronization of clocks between Hawkbit and the devices, the logs from SWUpdate consistently show:

```
[TRACE] : SWUPDATE running : [parse_reply] : Got channel reply: {"id":"1","deployment":{"download":"attempt","update":"skip","maintenanceWindow":"unavailable","chunks":[...]}}
```

The Hawkbit server is correctly providing updates during each poll, but the SWUpdate client always receives the `maintenanceWindow` status as "unavailable," which results in updates being skipped.

### Actions Taken So Far
- Verified that the clocks on all machines (Hawkbit server and target devices) are synchronized.
- The cron expression for the maintenance window is configured properly (e.g., `"schedule": "0 30 10 14 11 ? 2024"`).
- Using the Suricatta module of SWUpdate to communicate with Hawkbit. Communication between Hawkbit and SWUpdate works well, except for this maintenance window issue.

### Questions
1. Is there any specific configuration required on SWUpdate to ensure it respects the maintenance window (`maintenanceWindow`)?
2. Have there been any fixes related to this issue in SWUpdate versions released after 2023.05?
3. Hawkbit is providing updates on each polling, but I would like to ensure that devices only apply updates during the specified maintenance window. Is there a way to configure Hawkbit to enforce that updates are only sent during that maintenance window?
4. Could this issue be related to the cron expression or the interpretation of the cron format by SWUpdate? If yes, is there a recommended format that should be used?

**Environment:**
- Hawkbit Version: 0.6.1
- SWUpdate Version: 2023.05
- Using Suricatta module for communication.

Any help or insight into resolving this issue would be greatly appreciated.

**Comment by FabioPetry18** [comment]
to scheduled a update, use rollout, to imediatelly update a target, can use rollout or AssignDS!

**Comment by avgustinmm** [comment]
> Hi @FabioPetry18 , what do you mean by "skip or update immediately"? AFAIK, the maintenance window is just an instruction to the controller when to perform the software update. However, hawkBit will return the update on every poll.

Seems, I was wrong here - it seems that the maintenance window is not sent to the device with details but just as current status - available / unavailable at the moment (calculated by the server). 
It's a little bit surprising for me - device may never ping in such window. Probably the response shall be extended not only with the status but also with the details allowing the device (if desired) to calculate the "availability".


> `maintenanceWindow` Always Returning as "unavailable" in Hawkbit + SWUpdate**
>
@Edu4rdo00 , you can check the availability calculation (and possibly debug) in JpaAction,.isMaintenanceWindowAvailable
