### ISSUE TITLE
REMOVE_ARTIFACT is forbidden!

### ISSUE THREAD

**Issue by FabioPetry18** [eclipse-hawkbit/hawkbit#2082]
I'm trying to delete a artifact but I was received REMOVE_ARTIFACT is forbidden!

but some i can delete!

someone can help me?

**Comment by avgustinmm** [comment]
PS: what is the error you get? Doesn't it contain hint that it is LockedException?

**Comment by FabioPetry18** [comment]
I received this error:

HTTP 423
{
    "exceptionClass": "org.eclipse.hawkbit.repository.exception.LockedException",
    "errorCode": "hawkbit.server.error.locked",
    "message": "JpaSoftwareModule with given identifier {10} is locked and REMOVE_ARTIFACT is forbidden!"
}

**Comment by FabioPetry18** [comment]
How unlock a softwareModule?
In my UI I made the ds, sw and artifact all one for less complexity, when I want to delete them I was trying in this order:
delete ds -> delete artifact -> delete SW

**Comment by FabioPetry18** [comment]
I made a put with in DS and SW
{
            "locked": false
}
and it's works!

thank you!
